
WITH CTE_PLAN_TYPE AS (
											
											SELECT PLAN_TYPE,PP.PLAN_ID,MAX(ME.PLAN_VERSION_ID) IN_PLAN_VERSION_ID,
											PP.PERIOD_ID,RCP.START_DATE V_QTR_START_DATE,RCP.END_DATE V_QTR_END_DATE FROM PR_PLAN PP
											INNER JOIN REF_CAL_PERIOD RCP ON RCP.PERIOD_ID = PP.PERIOD_ID AND PERIOD_TYPE_CD = 'Q'
											INNER JOIN MODEL_EXEC ME ON ME.PLAN_ID = PP.PLAN_ID AND ME.MEDIA_OUTLET_ID = PP.MEDIA_OUTLET_ID AND ME.EXEC_STATUS_CD='C'
											WHERE PP.PLAN_ID = 447  -- PARAM1
											AND PP.MEDIA_OUTLET_ID = 96   -- PARAM3
											GROUP BY PP.PLAN_ID,PLAN_TYPE,PP.PERIOD_ID,RCP.START_DATE,RCP.END_DATE
										) -- SELECT * FROM CTE_PLAN_TYPE;
										,CTE_PAST_PLAN AS ( 
											SELECT IFNULL(PP.PLAN_ID,0) PLAN_ID,MAX(PLAN_VERSION_ID) V_PAST_PLAN_VERSION_ID,
											PP.PERIOD_ID FROM PR_PLAN PP
												INNER JOIN MODEL_EXEC ME ON ME.PLAN_ID = PP.PLAN_ID AND EXEC_STATUS_CD = 'C'
												WHERE PERIOD_ID=(SELECT PP.PERIOD_ID - 1 FROM PR_PLAN PP WHERE PLAN_ID = 447  -- PARAM1 
																AND PP.MEDIA_OUTLET_ID = 96   -- PARAM3 
																AND PLAN_TYPE= (SELECT PLAN_TYPE FROM CTE_PLAN_TYPE)) 
												AND PP.MEDIA_OUTLET_ID=96   -- PARAM3 
												AND ACTIVE_YN='Y' 
												AND PLAN_TYPE=(SELECT PLAN_TYPE FROM CTE_PLAN_TYPE)
												GROUP BY PP.PLAN_ID,PP.PERIOD_ID
										) -- SELECT * FROM CTE_PAST_PLAN;
										, CTE_DEFAULT_DEMO AS (
											SELECT DEMO_ID FROM REF_MEDIA_OUTLET_DEMO WHERE MEDIA_OUTLET_ID = 96   -- PARAM3
											AND DEFAULT_YN = 'Y'
										)  -- SELECT * FROM CTE_DEFAULT_DEMO;
										,CTE_MAP_END_DATE AS(
											SELECT END_DATE V_MAP_END_DATE FROM REF_CAL_PERIOD 
											WHERE PERIOD_ID = (SELECT PERIOD_ID + 1 FROM CTE_PLAN_TYPE) AND PERIOD_TYPE_CD = 'Q'
										) -- SELECT * FROM CTE_MAP_END_DATE;
										,CTE_PAST_QTR_DATA AS (
											SELECT 		
													PPP.PLAN_ID,
													PPP.PLAN_VERSION_ID,
													PPP.PROJECT_ID,
													PPP.ON_MAP_PREMIER_DATE,
													1 AS EPISODE_ID,
													PPP.STATUS_CD,
													PPP.PROJ_GRP,
													PPP.PROJ_REACH_PERCENT,
													PPP.USER_COMMENT,
													PPP.NETWORK_TARGET_DEMO_ID,
													'Y' AS PAST_QTR_PROJECT_FLAG,
													PPP.DISPLAY_SEQ,
													PPP.PROJ_PRIORITY PRIORITY1,
													PPP.TARGET_REACH_PCT TARGET_REACH1,
													PPP.TARGET_GRP TARGET_GRP1,
													PPP.CLUSTER_ID, 
													-- PPP.PROJ_REACH_PERCENT PROJ_PLANNED_REACH,
													-- PPP.PROJ_GRP PROJ_PLANNED_GRP, 
													PPP.ON_MAP_START_DATE,
													PPP.ON_MAP_END_DATE,
													PPP.PHASE_TYPE,
													CASE WHEN PPP.EPISODE_PRIORITY=0 THEN NULL ELSE PPP.EPISODE_PRIORITY END AS EPISODE_PRIORITY,
													PPP.NO_OF_EPISODE,
													PPP.ON_MAP_DEMO AS DEMO_ID,
													PPP.SEGMENT,
													PPP.FREQUENCY,
													PPP.CAMPAIGN_GOAL_ID,
													'PAST LAUNCH' PHASE_DUR_TYPE
												FROM 
												(	SELECT DISTINCT PPS.PLAN_ID, PPS.PLAN_VERSION_ID, PPS.PROJECT_ID, PPS.ACTIVE_YN, 
														PPS.MEDIA_OUTLET_ID, PPS.CAMPAIGN_GOAL_ID
														FROM PR_PLAN_SCHEDULE PPS 
														JOIN PR_PLAN P on P.PLAN_ID=PPS.PLAN_ID and PPS.PLAN_VERSION_ID=0 
														AND P.MEDIA_OUTLET_ID= 96 
														AND P.PLAN_TYPE=(SELECT PLAN_TYPE FROM CTE_PLAN_TYPE) and P.PERIOD_ID < (SELECT PERIOD_ID FROM CTE_PLAN_TYPE)
														AND PPS.START_DATE BETWEEN (SELECT V_QTR_START_DATE FROM CTE_PLAN_TYPE) 
														AND (SELECT V_QTR_END_DATE FROM CTE_PLAN_TYPE) 
														AND PPS.ACTIVE_YN='Y'
												) PPS   
												JOIN PR_PLAN_PROJECT PPP ON PPP.PLAN_ID=PPS.PLAN_ID AND PPP.PROJECT_ID=PPS.PROJECT_ID 
												and PPP.PLAN_VERSION_ID= (select MAX(PLAN_VERSION_ID) from MODEL_EXEC M where PLAN_ID=PPS.PLAN_ID and M.MODEL_TYPE_ID=1 
												AND M.MEDIA_OUTLET_ID = 96   -- PARAM3  
												AND M.EXEC_STATUS_CD='C')
												AND PPP.PLAN_ID<>447  -- PARAM1


												UNION

												SELECT 		
													PPP.PLAN_ID,
													PPP.PLAN_VERSION_ID,
													PPP.PROJECT_ID,
													PPP.ON_MAP_PREMIER_DATE,
													PPPE.EPISODE_ID AS EPISODE_ID,
													PPP.STATUS_CD,
													PPP.PROJ_GRP,
													PPP.PROJ_REACH_PERCENT,
													PPP.USER_COMMENT,
													PPP.NETWORK_TARGET_DEMO_ID,
													'Y' AS PAST_QTR_PROJECT_FLAG,
													PPP.DISPLAY_SEQ,
													PPP.PROJ_PRIORITY PRIORITY1,
													PPP.TARGET_REACH_PCT TARGET_REACH1,
													PPP.TARGET_GRP TARGET_GRP1,
													PPP.CLUSTER_ID, -- change 2.7.5 additional
													-- PPP.PROJ_REACH_PERCENT PROJ_PLANNED_REACH,
													-- PPP.PROJ_GRP PROJ_PLANNED_GRP, -- change 2.7.5 additional
													PPP.ON_MAP_START_DATE,
													PPP.ON_MAP_END_DATE,
													PPP.PHASE_TYPE,
													CASE WHEN PPP.EPISODE_PRIORITY=0 THEN NULL ELSE PPP.EPISODE_PRIORITY END AS EPISODE_PRIORITY,
													PPP.NO_OF_EPISODE,
													PPP.ON_MAP_DEMO AS DEMO_ID,
													PPP.SEGMENT,
													PPP.FREQUENCY,
													PPP.CAMPAIGN_GOAL_ID,
													'PAST EP' PHASE_DUR_TYPE
												FROM 
												(	SELECT DISTINCT PPS.PLAN_ID, PPS.PLAN_VERSION_ID, PPS.PROJECT_ID, PPS.ACTIVE_YN, PPS.MEDIA_OUTLET_ID,
														PPS.CAMPAIGN_GOAL_ID
														FROM PR_PLAN_SCHEDULE_EPISODE PPS 
														JOIN PR_PLAN P on P.PLAN_ID=PPS.PLAN_ID and PPS.PLAN_VERSION_ID=0 
														AND P.MEDIA_OUTLET_ID=96   -- PARAM3  
														AND P.PLAN_TYPE= (SELECT PLAN_TYPE FROM CTE_PLAN_TYPE) and P.PERIOD_ID < (SELECT PERIOD_ID FROM CTE_PLAN_TYPE)
														AND PPS.START_DATE between (SELECT V_QTR_START_DATE FROM CTE_PLAN_TYPE) 
														AND (SELECT V_QTR_END_DATE FROM CTE_PLAN_TYPE)  AND PPS.ACTIVE_YN='Y'
												) PPS   
												JOIN PR_PLAN_PROJECT PPP ON PPP.PLAN_ID=PPS.PLAN_ID AND PPP.PROJECT_ID=PPS.PROJECT_ID 
												and PPP.PLAN_VERSION_ID= (select MAX(PLAN_VERSION_ID) from MODEL_EXEC M where PLAN_ID=PPS.PLAN_ID and M.MODEL_TYPE_ID=1 
												AND M.MEDIA_OUTLET_ID=96   -- PARAM3
												and M.EXEC_STATUS_CD='C')
												and PPP.PLAN_ID<>447  -- PARAM1
												INNER JOIN PR_PLAN_PROJECT_EPISODE PPPE
												ON PPP.PROJECT_ID=PPPE.PROJECT_ID AND PPP.PLAN_ID=PPPE.PLAN_ID AND PPP.PLAN_VERSION_ID=PPPE.PLAN_VERSION_ID
												WHERE NOT EXISTS 
												(
													SELECT 1 FROM PR_PLAN_SCHEDULE PPS1 
														JOIN PR_PLAN P on P.PLAN_ID=PPS1.PLAN_ID and PPS1.PLAN_VERSION_ID=0 
														AND P.MEDIA_OUTLET_ID=96   -- PARAM3 
														AND P.PLAN_TYPE=(SELECT PLAN_TYPE FROM CTE_PLAN_TYPE) 
														AND P.PERIOD_ID < (SELECT PERIOD_ID FROM CTE_PLAN_TYPE)
														AND PPS1.START_DATE BETWEEN (SELECT V_QTR_START_DATE FROM CTE_PLAN_TYPE)
														AND (SELECT V_QTR_END_DATE FROM CTE_PLAN_TYPE) AND PPS1.ACTIVE_YN='Y'
														WHERE PPS1.PROJECT_ID=PPP.PROJECT_ID
												)
										
										) -- SELECT * FROM CTE_PAST_QTR_DATA;
										,CTE_CUR_QTR_DATA AS (
											SELECT 		
													PPP.PLAN_ID,
													PPP.PLAN_VERSION_ID,
													PPP.PROJECT_ID,
													PPP.ON_MAP_PREMIER_DATE,
													1 AS EPISODE_ID,
													PPP.STATUS_CD,
													PPP.PROJ_GRP,
													PPP.PROJ_REACH_PERCENT,
													PPP.USER_COMMENT,
													PPP.NETWORK_TARGET_DEMO_ID,
													'N' AS PAST_QTR_PROJECT_FLAG,
													PPP.DISPLAY_SEQ,
													PPP.PROJ_PRIORITY PRIORITY1,
													PPP.TARGET_REACH_PCT TARGET_REACH1,
													PPP.TARGET_GRP TARGET_GRP1,
													PPP.CLUSTER_ID, 
													-- PPP.PROJ_REACH_PERCENT PROJ_PLANNED_REACH,
													-- PPP.PROJ_GRP PROJ_PLANNED_GRP,
													PPP.ON_MAP_START_DATE,
													PPP.ON_MAP_END_DATE,
													PPP.PHASE_TYPE,
													CASE WHEN PPP.EPISODE_PRIORITY=0 THEN NULL ELSE PPP.EPISODE_PRIORITY END AS EPISODE_PRIORITY,
													PPP.NO_OF_EPISODE,
													PPP.ON_MAP_DEMO AS DEMO_ID,
													PPP.SEGMENT,
													PPP.FREQUENCY,
													PPP.CAMPAIGN_GOAL_ID,
													'CUR LAUNCH' PHASE_DUR_TYPE
												FROM PR_PLAN_PROJECT PPP 
												WHERE PPP.PLAN_ID = 447  -- PARAM1 
												AND PPP.PLAN_VERSION_ID = (SELECT IN_PLAN_VERSION_ID FROM CTE_PLAN_TYPE) 
												AND PPP.CAMPAIGN_GOAL_ID >0 AND PPP.STATUS_CD <> 2

											UNION

											SELECT 		
													PPP.PLAN_ID,
													PPP.PLAN_VERSION_ID,
													PPP.PROJECT_ID,
													PPP.ON_MAP_PREMIER_DATE,
													PPPE.EPISODE_ID AS EPISODE_ID,
													PPP.STATUS_CD,
													PPP.PROJ_GRP,
													PPP.PROJ_REACH_PERCENT,
													PPP.USER_COMMENT,
													PPP.NETWORK_TARGET_DEMO_ID,
													'N' AS PAST_QTR_PROJECT_FLAG,
													PPP.DISPLAY_SEQ,
													PPP.PROJ_PRIORITY PRIORITY1,
													PPP.TARGET_REACH_PCT TARGET_REACH1,
													PPP.TARGET_GRP TARGET_GRP1,
													PPP.CLUSTER_ID,
													-- PPP.PROJ_REACH_PERCENT PROJ_PLANNED_REACH,
													-- PPP.PROJ_GRP PROJ_PLANNED_GRP, 
													PPP.ON_MAP_START_DATE,
													PPP.ON_MAP_END_DATE,
													PPP.PHASE_TYPE,
													CASE WHEN PPP.EPISODE_PRIORITY=0 THEN NULL ELSE PPP.EPISODE_PRIORITY END AS EPISODE_PRIORITY,
													PPP.NO_OF_EPISODE,
													PPP.ON_MAP_DEMO AS DEMO_ID,
													PPP.SEGMENT,
													PPP.FREQUENCY,
													PPP.CAMPAIGN_GOAL_ID,
													'CUR EP' PHASE_DUR_TYPE
												FROM PR_PLAN_PROJECT PPP
												INNER JOIN PR_PLAN_PROJECT_EPISODE PPPE
												ON PPP.PROJECT_ID=PPPE.PROJECT_ID AND PPP.PLAN_ID=PPPE.PLAN_ID AND PPP.PLAN_VERSION_ID=PPPE.PLAN_VERSION_ID
												AND PPP.PLAN_ID = 447  -- PARAM1  
												AND PPP.PLAN_VERSION_ID = (SELECT IN_PLAN_VERSION_ID FROM CTE_PLAN_TYPE)
												AND PPPE.CAMPAIGN_GOAL_ID>0 AND PPP.STATUS_CD <> 2
												WHERE NOT EXISTS 
												(
													SELECT 1 FROM PR_PLAN_PROJECT PPP1 
														WHERE PPP1.PLAN_ID = 447  -- PARAM1 
														AND PPP1.PLAN_VERSION_ID = (SELECT IN_PLAN_VERSION_ID FROM CTE_PLAN_TYPE) 
														AND PPP.PROJECT_ID=PPP1.PROJECT_ID AND PPP1.CAMPAIGN_GOAL_ID>0 AND PPP1.STATUS_CD <> 2
												)
												
										)-- SELECT * FROM CTE_CUR_QTR_DATA;
										,PROJ_DTL AS (
											SELECT * FROM CTE_PAST_QTR_DATA
											UNION 
											SELECT * FROM CTE_CUR_QTR_DATA
										) 
										-- SELECT * FROM PROJ_DTL;

										SELECT 
											PROJ_DTL.PROJECT_ID PROJECT_ID,
											PPR.NAME PROJECT_NAME,
											PROJ_DTL.ON_MAP_PREMIER_DATE AS PREMIERE_DATE, 
										
											PROJ_DTL.ON_MAP_START_DATE AS PROJ_START_DATE,
											PROJ_DTL.ON_MAP_END_DATE AS PROJ_END_DATE,
											RD.NAME DEMO,
											RD.DEMO_ID DEMO_ID,
											RCT.NAME TYPE,
											RS.SEGMENT_NAME AS SEGMENT,
											PROJ_DTL.PRIORITY1 PRIORITY,
											PROJ_DTL.FREQUENCY,
											PROJ_DTL.TARGET_REACH1 AS REACH,
											PROJ_DTL.TARGET_GRP1 AS GRP,
											PROJ_DTL.PROJ_REACH_PERCENT,
											RPS.NAME AS STATUS_CD,
											CEIL(CASE WHEN DATEDIFF(DAY,PROJ_DTL.ON_MAP_START_DATE,PROJ_DTL.ON_MAP_END_DATE)=0 THEN 1 
												ELSE DATEDIFF(DAY,PROJ_DTL.ON_MAP_START_DATE,PROJ_DTL.ON_MAP_END_DATE) END / 7) AS NO_OF_WEEKS,
											null CAMPAIGN_ID,
											W.START_DATE WEEK_START_DATE,
											CASE WHEN 1 = 1     --PARAM4 
												THEN SUM(PPS.PLANNED_UNITS)
													ELSE SUM(PPS.PLANNED_GRP)
											END AS PLANNED_UNITS,
											PPR.USER_COMMENT AS PROJECT_COMMENT,
											PROJ_DTL.PAST_QTR_PROJECT_FLAG AS PAST_PROJECT,
											RCT.DISPLAY_SEQ AS CAMPAIGN_DISPLAY_SEQ,
											PROJ_DTL.DISPLAY_SEQ AS PROJECT_DISPLAY_SEQ,
											CASE WHEN PPR.MEDIA_OUTLET_ID=96   -- PARAM3 
											THEN 1 ELSE 99 END AS NETWORK_DISPLAY_SEQ,
											SUM(PPS.PLANNED_GRP) PROJ_GRP,
											PPR.SCATTER_IMPS ,
											PPR.MEDIA_OUTLET_ID,
											RMO.SHORT_NAME AS MEDIA_OUTLET_NAME,
											PROJ_DTL.CLUSTER_ID, 
											RC.CLUSTER_NAME AS CLUSTER_NAME, 
											PROJ_DTL.PROJ_REACH_PERCENT PROJ_PLANNED_REACH,
											PROJ_DTL.PROJ_GRP PROJ_PLANNED_GRP,
											PPR.EVENT_TYPE_ID AS EVENT_ID,
											RET.EVENT_TYPE_NAME AS EVENT_NAME,
											PPR.SUBEVENT_ID ,
											RES.SUBEVENT_NAME,
											PROJ_DTL.PHASE_TYPE,
											RPT.DESCRIPTION AS PH_DESC,
											PROJ_DTL.EPISODE_PRIORITY,
											PROJ_DTL.NO_OF_EPISODE,
											PROJ_DTL.PLAN_ID


										FROM PROJ_DTL 
										JOIN PR_PROJECT PPR ON  PPR.PROJECT_ID = PROJ_DTL.PROJECT_ID 
											AND PPR.PROJECT_TYPE=(SELECT PLAN_TYPE FROM CTE_PLAN_TYPE)
										
										JOIN REF_SEGMENT RS ON PROJ_DTL.SEGMENT=RS.SEGMENT_ID
										JOIN REF_MEDIA_OUTLET RMO ON PPR.MEDIA_OUTLET_ID=RMO.MEDIA_OUTLET_ID
										JOIN REF_DEMO RD ON PROJ_DTL.DEMO_ID = RD.DEMO_ID 
										JOIN REF_CAL_PERIOD RCP ON RCP.NAME = '1Q25'  -- PARAM2 
										AND RCP.PERIOD_TYPE_CD = 'Q'
										JOIN REF_CAL_PERIOD W ON W.PERIOD_TYPE_CD = 'W'
											AND W.START_DATE >= (SELECT V_QTR_START_DATE FROM CTE_PLAN_TYPE) 
											AND W.START_DATE<= (SELECT V_MAP_END_DATE FROM CTE_MAP_END_DATE)
										LEFT JOIN REF_PROJECT_PLAN_TYPE RPT ON RPT.TYPE_ID = PROJ_DTL.PHASE_TYPE
										LEFT JOIN REF_PLAN_STATUS RPS ON RPS.PLAN_STATUS_ID=PROJ_DTL.STATUS_CD
										LEFT JOIN REF_CLUSTER RC on PROJ_DTL.CLUSTER_ID=RC.CLUSTER_ID	
										LEFT JOIN REF_CAMPAIGN_TYPE RCT ON PPR.CAMPAIGN_TYPE_ID = RCT.CAMPAIGN_TYPE_ID
										LEFT JOIN REF_2E_EVENT_SUBTYPE_PROJECT RES ON RES.SUBEVENT_ID=PPR.SUBEVENT_ID
										LEFT JOIN REF_2E_EVENT_TYPE RET ON RET.EVENT_TYPE_ID=PPR.EVENT_TYPE_ID
										LEFT JOIN PR_PLAN_SCHEDULE PPS ON PPS.PLAN_ID = PROJ_DTL.PLAN_ID
													AND PPS.START_DATE BETWEEN W.START_DATE AND W.END_DATE
													AND PPS.CAMPAIGN_GOAL_ID = PROJ_DTL.CAMPAIGN_GOAL_ID
													AND PPS.ACTIVE_YN = 'Y' AND PPS.PLAN_VERSION_ID = 0

										GROUP BY 
										PROJ_DTL.PROJECT_ID,
												PPR.NAME,
												W.START_DATE,
												PROJ_DTL.ON_MAP_PREMIER_DATE, 
												PROJ_DTL.ON_MAP_START_DATE,
												PROJ_DTL.ON_MAP_END_DATE,
												RD.NAME,
												RD.DEMO_ID,
												RCT.NAME,
												RS.SEGMENT_NAME,
												PROJ_DTL.PRIORITY1,
												PROJ_DTL.FREQUENCY,
												PROJ_DTL.TARGET_REACH1,
												PROJ_DTL.TARGET_GRP1,
												PROJ_DTL.PROJ_REACH_PERCENT,
												RPS.NAME,
												NO_OF_WEEKS,
												CAMPAIGN_ID,
												PPR.USER_COMMENT,
												PROJ_DTL.PAST_QTR_PROJECT_FLAG,
												RCT.DISPLAY_SEQ,
												PROJ_DTL.DISPLAY_SEQ,
												NETWORK_DISPLAY_SEQ,
												PPR.SCATTER_IMPS ,
												PPR.MEDIA_OUTLET_ID,
												RMO.SHORT_NAME,
												PROJ_DTL.CLUSTER_ID, 
												RC.CLUSTER_NAME, 
												PROJ_DTL.PROJ_REACH_PERCENT,
												PROJ_DTL.PROJ_GRP,
												PPR.EVENT_TYPE_ID,
												RET.EVENT_TYPE_NAME,
												PPR.SUBEVENT_ID ,
												RES.SUBEVENT_NAME,
												PROJ_DTL.PHASE_TYPE,
												RPT.DESCRIPTION,
												PROJ_DTL.EPISODE_PRIORITY,
												PROJ_DTL.NO_OF_EPISODE,
												PROJ_DTL.PLAN_ID
												ORDER BY PROJ_DTL.DISPLAY_SEQ , PPR.NAME , W.START_DATE , PAST_QTR_PROJECT_FLAG;

